# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(298, 237)
        Settings.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.gridLayout = QtWidgets.QGridLayout(Settings)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Settings)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.le_source = QtWidgets.QLineEdit(Settings)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.le_source.setFont(font)
        self.le_source.setAlignment(QtCore.Qt.AlignCenter)
        self.le_source.setObjectName("le_source")
        self.gridLayout.addWidget(self.le_source, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Settings)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.dsb_pos_x = QtWidgets.QDoubleSpinBox(Settings)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dsb_pos_x.setFont(font)
        self.dsb_pos_x.setAlignment(QtCore.Qt.AlignCenter)
        self.dsb_pos_x.setMaximum(1000.0)
        self.dsb_pos_x.setObjectName("dsb_pos_x")
        self.gridLayout.addWidget(self.dsb_pos_x, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Settings)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.dsb_pos_y = QtWidgets.QDoubleSpinBox(Settings)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.dsb_pos_y.setFont(font)
        self.dsb_pos_y.setAlignment(QtCore.Qt.AlignCenter)
        self.dsb_pos_y.setMaximum(1000.0)
        self.dsb_pos_y.setObjectName("dsb_pos_y")
        self.gridLayout.addWidget(self.dsb_pos_y, 2, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 3, 0, 1, 2)

        self.retranslateUi(Settings)
        self.buttonBox.accepted.connect(Settings.accept) # type: ignore
        self.buttonBox.rejected.connect(Settings.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Dialog"))
        self.label.setText(_translate("Settings", "Source"))
        self.label_2.setText(_translate("Settings", "Reference X"))
        self.label_3.setText(_translate("Settings", "Reference Y"))
